version: 0.2

phases:
  install:
    commands:
      - echo "Installing NGINX on Amazon Linux"
      - sudo yum update -y
      - sudo amazon-linux-extras install -y nginx1
  build:
    commands:
      - echo "Build started on `date`"
      - cp index.html /usr/share/nginx/html/
  post_build:
    commands:
      - echo "Configuring NGINX"
      - sudo systemctl enable nginx
      - sudo systemctl start nginx

artifacts:
  files:
    - /usr/share/nginx/html/index.html
